### ISSUE TITLE
do we need a exact node engine version here?

### ISSUE THREAD

**Issue by ClemensSahs** [thenativeweb/buntstift#454]
error buntstift@5.0.0: The engine "node" is incompatible with this module. Expected version "16.6.2". Got "16.8.0"

**Comment by goloroden** [comment]
@ClemensSahs This is actually not needed anymore (and wrong, by the way, too), so we can safely remove it. Respectively: It already has been removed a while ago, we just did not publish a new version. I'll do that in a minute.

**Comment by goloroden** [comment]
@ClemensSahs `buntstift@5.0.1` has just been released, and it should fix this issue. Could you  maybe verify whether it works now as expected, and (if so) close this issue?

**Comment by ClemensSahs** [comment]
yes this works fine now
