### ISSUE TITLE
How to use buntstift.table to display contents of array

### ISSUE THREAD

**Issue by quarterpi** [thenativeweb/buntstift#9]
I have an array of objects that I want to display to the user. 
It looks something like:
```
[
  {current:'current', latest:{name:'name', date:'date'}},
  {current:'current', latest:{name:'name', date:'date'}},
  {current:'current', latest:{name:'name', date:'date'}},
  {current:'current', latest:{name:'name', date:'date'}},
  {current:'current', latest:{name:'name', date:'date'}},
  ...
]
```
I love that buntstift.table makes everything pretty for you, but it seems limited in this case. If I knew that the array was only going to have length x I could just hardcode it in. However, in my case the array is dynamic. Please tell me this is a supported feature and I'm just not understanding how it works?
Thanks

**Comment by yeldiRium** [comment]
Hi quarterpi!

`buntstift.table` expects a two-dimensional array. So you can either wrap your data structure in an outer list like so:
```javascript
[[
  {current:'current', latest:{name:'name', date:'date'}},
  ...
]]
```
which would get you a table with all objects in one line. Or you can wrap each element like so:
```javascript
[
  [{current:'current', latest:{name:'name', date:'date'}}],
  ...
]
```
which would get you a table with all objects in one column.

Both have the limitation that the objects are displayed as `[object Object]`. There is no direct support for pretty-printing objects at the moment, so you'd have to stringify them manually.

My first attempt to stringify the objects and display them in one column would be this:
```javascript
const data = ... // your datastructure from above
buntstift.table(data.map(value => [JSON.stringify(value)]))
```
This wraps each value in an array to display them on a separate row each and stringifies the values inside.

Is this what you want or am i missing something?

**Comment by quarterpi** [comment]
@yeldiRium Sorry it took me so long to reply to this. That's what I was looking for. Thank you!
